### ISSUE TITLE
SimHub plugin to publish telemetry to MQTT endpoint

### ISSUE THREAD

**Issue by durandom** [b4mad/racing#1]
## User Story

As a SimHub user I can install a plugin to publish live game data to an MQTT endpoint

## Acceptance Criteria

- [ ] https://github.com/dotnet/MQTTnet client is used
- [ ] Plugin configuration page with
  - [ ] User / Password authentication
  - [ ] Topic URL
  - [ ] sample rate in milliseconds
  - [ ] upload rate in seconds
- [ ] payload is JSON with
  - [ ] “time” field with UNIX timestamp milliseconds UTC timezone
  - [ ] all SimHub normalized fields (e.g. throttle, brake, map_position)
  - [ ] all game-specific fields for iRacing or Automobilista2 game
- [ ] telemetry is sampled at configurable sample rate and added to the JSON payload
- [ ] payload is buffered and uploaded at configured upload rate
- [ ] payload is compressed in gzip
- [ ] telemetry sampling is not blocked during upload - use threads
- [ ] sampling / uploading starts whenever a game enters practice/qualifying/race
- [ ] plugin can also upload data from a saved session in SimHup (replay)
- [ ] Documentation to build plugin

In order to avoid saturation of upload bandwidth and improve the compression ratio, we don't want to stream the JSON payloads, but instead, collect samples for a certain period (e.g. 10 seconds), then compress the payload and then publish the payload to the topic (upload).

## local development

Use the [docker-compose](https://github.com/b4mad/racing#docker-compose-stack) setup to develop locally

## Use case
Racing teams and individual drivers are able to stream their telemetry data to the platform.
They can visualize the data in existing and customized dashboards and execute functions provided by the data storage engine.

## Architecture
[SimHub](https://www.simhubdash.com/) is able to read telemetry from a multitude of games and unifies the format, it also provides a [plugin](https://github.com/SHWotever/SimHub/issues/692) architecture in C#. 
[MQTT](https://mqtt.org/) is a messaging standard. [Telegraf](https://www.influxdata.com/time-series-platform/telegraf/) can interface to the MQTT broker and send the data into an [Influx](https://www.influxdata.com/) database, which in turn can be visualized by [Grafana](https://grafana.com/) dashboards. See [b4mad.racing architecture](https://docs.google.com/presentation/d/1_TUkDxYGnmKEc1n0BYs2MfnqbHU9u3DNrolwiyty0Og/edit#slide=id.p)

**Comment by durandom** [comment]
it's done. Thanks so much to @SHWotever and @LukasLichten

**Comment by egranto** [comment]
can you explain me how to do it i follow your steps and i was able to do it with telegram and crewchief, but i rather prefer simhub (F123)
