### ISSUE TITLE
missing ENV?

### ISSUE THREAD

**Issue by goern** [b4mad/racing#107]
is the init container missign two env vars? 

https://github.com/b4mad/racing/blob/7cae693ca93876102bb9b59d3fd3c61aa24bd707/manifests/paddock/base/deployment_config.yaml#L65

/kind question
/kind bug
/priority critical-urgent
/assign durandom

**Comment by durandom** [comment]
https://github.com/b4mad/racing/blob/v0.1.12/manifests/paddock/overlays/smaug/paddock-settings.enc.yaml#L7-L9
