### ISSUE TITLE
refactor all secrets into Secret

### ISSUE THREAD

**Issue by goern** [b4mad/racing#17]
Let's refactor all the tokens and password and... into a Secret managed by kustomize+argocd, helm values and config files need to use ENV, deployments need to use volume mounted from Secret

**Comment by durandom** [comment]
make use of the vault instance on operate first

**Comment by goern** [comment]
rn we us SealedSecrets via gitops for this, for example https://github.com/b4mad/racing/blob/main/manifests/env/phobos/paddock-settings.sealed.yaml

/close
