### ISSUE TITLE
can you explain me how to do it i follow your steps and i was able to do it with telegram and crewchief, but i rather prefer simhub (F123)

### ISSUE THREAD

**Issue by goern** [b4mad/racing#322]
/kind feature
/kind question
/assign durandom
   

           can you explain me how to do it i follow your steps and i was able to do it with telegram and crewchief, but i rather prefer simhub (F123)

_Originally posted by @egranto in https://github.com/b4mad/racing/issues/1#issuecomment-1605517186_

**Comment by durandom** [comment]
@egranto the SimHub pipeline is not functional anymore. 
The whole purpose is to provide advice and feedback while driving, therefore we default to CrewChief.

What exactly are you trying to do?

**Comment by egranto** [comment]
well the same you did in CrewChief (i use the same idea as you in B4mad) send telemetry to MQTT so i can use my ESP2866 rev light and color flags, also do an analysis in grafana by sending data to influxDB also consume by Homeassistant, but now i start playing F123 and crewchief not supported yet, i'm using simhub to UDP relay... why not send the data from there? sadly i came late to the party.   

My Grafana Panel
![image](https://github.com/b4mad/racing/assets/60528368/13fb3c1e-2649-4d56-90ea-6ae46a76f375)

Thanks for the Telegraf idea by the way

**Comment by durandom** [comment]
@egranto if it's just for sending telemetry then it should work. You'd need to setup a telegraf endpoint of course.
Your dashboard looks neat. If you like we can setup an endpoint at telemetry.b4mad.racing and store the data in our influxdb and visualize in our grafana instance. Unless you want to maintain your own local pipeline.

**Comment by egranto** [comment]
you already answer my question thanks 
and yes i keep it local because i'm sending more data than the default output 

We can close the case now

**Comment by durandom** [comment]
sure. If you like to share your dashboards and make them available to the community, I'm happy to host a pipeline and the dashboards for others. Should be straightforward to set it up.

/close
