### ISSUE TITLE
extended dashboard query timeout

### ISSUE THREAD

**Issue by durandom** [b4mad/racing#355]
`ts=2023-07-18T08:16:24.777994Z lvl=debug msg=Request log_id=0j5~Tck0000 service=http method=POST host=influxdb2:8086 path=/api/v2/query query="org=b4mad" proto=HTTP/1.1 status_code=499 response_size=88 content_length=535 referrer= remote=10.128.0.151:36232 user_agent=influxdb-client-go took=1393622.577ms error="internal error" error_code="internal error" body="{\"dialect\":{\"annotations\":[\"datatype\",\"group\",\"default\"],\"delimiter\":\",\",\"header\":true},\"query\":\"from(bucket: \\\"racing\\\")\\r\\n  |\\u003e range(start: -1y, stop: now())\\r\\n  |\\u003e filter(fn: (r) =\\u003e r[\\\"_measurement\\\"] == \\\"laps_cc\\\")\\r\\n  |\\u003e filter(fn: (r) =\\u003e r[\\\"_field\\\"] == \\\"Gear\\\")\\r\\n  |\\u003e keep(columns: [\\\"user\\\", \\\"_time\\\", \\\"_value\\\"])\\r\\n  |\\u003e sort(columns: [\\\"_time\\\"], desc: false)\\r\\n  |\\u003e first()\\r\\n  |\\u003e group(columns: [])\\r\\n  |\\u003e drop(columns: [\\\"_value\\\",\\\"_time\\\"])\",\"type\":\"flux\"}"`

This query produces a timeout (HTTP code 499) and it also leads to a long (couple of minutes) CPU spike on the influx server.

@egranto do you know which graph is using this query and can we remove it?

**Comment by goern** [comment]
ping, any update on this?!

**Comment by egranto** [comment]
User variable, but that extend need to be deleted. 

i had pull 361 also but as it wasn't push i keep working on it  offline 
(i even work on all dashboads)

**Comment by durandom** [comment]
I think this is fixed in the new dashboards
