### ISSUE TITLE
pitwall detail dashboard is broken

### ISSUE THREAD

**Issue by goern** [b4mad/racing#378]
https://pitwall.b4mad.racing/d/e12c7ccb-ff51-4525-b5da-0d783a1019ef/b4mad-session-details?orgId=1&var-Speed=3.6&var-user=goern&var-SessionId=1691505752&var-SessionStart=&var-SessionEnd=&var-SessionLen=551 is one example of the data not being displayed. And https://openshift-gitops-server-openshift-gitops.apps.nostromo.erdgeschoss.b4mad.emea.operate-first.cloud/applications/openshift-gitops/b4mad-racing?resource=&operation=true is giving a sync error:

```
GrafanaDashboard.grafana.integreatly.org "details-extended" is invalid: metadata.annotations: Too long: must have at most 262144 bytes
```

is this known/acceptable?

/kind bug
/priority important-soon
/assign durandom

**Comment by egranto** [comment]
Details only work if you had a valid session and full data will display only if you send it 

https://pitwall.b4mad.racing/d/e12c7ccb-ff51-4525-b5da-0d783a1019ef/b4mad-session-details?orgId=1&var-Speed=3.6&var-user=e%20Grant&var-SessionId=1691425492&var-SessionStart=1691403894367179300&var-SessionEnd=1691403904146594000&var-SessionLen=10&from=now-30d&to=now

Jim without extended Details 

https://pitwall.b4mad.racing/d/e12c7ccb-ff51-4525-b5da-0d783a1019ef/b4mad-session-details?orgId=1&var-Speed=3.6&var-user=Jim&var-SessionId=1690739325&var-SessionStart=1690775324669664300&var-SessionEnd=1690775465512996900&var-SessionLen=141&from=1690775324517&to=1690775467514

**Comment by durandom** [comment]
the argocd sync error is know.
one workaround would be to move the dashboard source into it's own file and reference the file via a URL

https://grafana-operator.github.io/grafana-operator/docs/dashboards/#url

**Comment by durandom** [comment]
a manual workaround is to us `replace resource` in argocd or via the cli `oc replace -k grafana`

**Comment by goern** [comment]
BTW, on nostromo-stage it seems to work ok?! See https://openshift-gitops-server-openshift-gitops.apps.nostromo.erdgeschoss.b4mad.emea.operate-first.cloud/applications/openshift-gitops/b4mad-racing-nostromo-stage?resource=&node=grafana.integreatly.org%2FGrafanaDashboard%2Fb4mad-racing-stage%2Fdetails-extended%2F0&tab=summary

**Comment by durandom** [comment]
everything should be fine now. I extracted the dashboard jsons into their own files
