### ISSUE TITLE
psql backup job fails

### ISSUE THREAD

**Issue by durandom** [b4mad/racing#399]
time="2023-08-22T01:00:19Z" level=info msg="crunchy-pgbackrest starts"
time="2023-08-22T01:00:19Z" level=info msg="debug flag set to false"
time="2023-08-22T01:00:19Z" level=info msg="backrest backup command requested"
time="2023-08-22T01:00:19Z" level=info msg="command to execute is [pgbackrest backup --stanza=db --repo=1 --type=diff]"
time="2023-08-22T01:00:19Z" level=info msg="output=[]"
time="2023-08-22T01:00:19Z" level=info msg="stderr=[]"
time="2023-08-22T01:00:19Z" level=fatal msg="pods \"db-repo-host-0\" is forbidden: exec operation is not allowed because the pod's security context exceeds your permissions: pods \"db-repo-host-0\" is forbidden: unable to validate against any security context constraint: [provider \"anyuid\": Forbidden: not usable by user or serviceaccount, provider restricted-v2: .spec.securityContext.fsGroup: Invalid value: []int64{1000750000}: 1000750000 is not an allowed group, provider restricted-v2: .spec.securityContext.seLinuxOptions.level: Invalid value: \"s0:c27,c24\": must be s0:c28,c22, provider restricted-v2: .initContainers[0].runAsUser: Invalid value: 1000750000: must be in the ranges: [1000800000, 1000809999], provider restricted-v2: .initContainers[0].seLinuxOptions.level: Invalid value: \"s0:c27,c24\": must be s0:c28,c22, provider restricted-v2: .initContainers[1].runAsUser: Invalid value: 1000750000: must be in the ranges: [1000800000, 1000809999], provider restricted-v2: .initContainers[1].seLinuxOptions.level: Invalid value: \"s0:c27,c24\": must be s0:c28,c22, provider restricted-v2: .containers[0].runAsUser: Invalid value: 1000750000: must be in the ranges: [1000800000, 1000809999], provider restricted-v2: .containers[0].seLinuxOptions.level: Invalid value: \"s0:c27,c24\": must be s0:c28,c22, provider restricted-v2: .containers[1].runAsUser: Invalid value: 1000750000: must be in the ranges: [1000800000, 1000809999], provider restricted-v2: .containers[1].seLinuxOptions.level: Invalid value: \"s0:c27,c24\": must be s0:c28,c22, provider \"restricted\": Forbidden: not usable by user or serviceaccount, provider \"nonroot-v2\": Forbidden: not usable by user or serviceaccount, provider \"nonroot\": Forbidden: not usable by user or serviceaccount, provider \"hostmount-anyuid\": Forbidden: not usable by user or serviceaccount, provider \"machine-api-termination-handler\": Forbidden: not usable by user or serviceaccount, provider \"hostnetwork-v2\": Forbidden: not usable by user or serviceaccount, provider \"hostnetwork\": Forbidden: not usable by user or serviceaccount, provider \"hostaccess\": Forbidden: not usable by user or serviceaccount, provider \"lvms-vgmanager\": Forbidden: not usable by user or serviceaccount, provider \"lvms-topolvm-node\": Forbidden: not usable by user or serviceaccount, provider \"synology-csi-scc\": Forbidden: not usable by user or serviceaccount, provider \"node-exporter\": Forbidden: not usable by user or serviceaccount, provider \"privileged\": Forbidden: not usable by user or serviceaccount]"

**Comment by goern** [comment]
This is a pod log from a pod created by `db-repo1-diff` cronjob.
