### ISSUE TITLE
extract track guides from telemetry

### ISSUE THREAD

**Issue by durandom** [b4mad/racing#75]
for the pitcrew to work, we need track information in CVS files, like https://github.com/b4mad/racing/blob/main/pitcrew/Ferrari%20488%20GT3%20Evo%202020-oschersleben%20gp.csv

These are currently built manually 😢 

Let's use some data science to create them automatically, maybe like this

1. Find all the laps for a given game/track/car combo
2. extract the mean for all lowest gears in the turns

**Comment by adenoz** [comment]
I've only just stumbled upon this project but thought to offer a couple of things here. I wouldn't include all laps. You should only use say the fastest 25% of laps. Slow laps will contain bad inputs and times which will be 'outliers'. Outliers can heavily impact mean values, which could result in the mean being moved away from where the 'centre' of the desired data actually is.

But overall agree with intent to harness power of the crowd here. Interesting stuff.

**Comment by durandom** [comment]
@adenoz thanks for the input. Do you want to take a crack at this?

https://github.com/b4mad/racing/blob/main/notebooks/exploratory_data_analysis.ipynb is a notebook to get started with accessing the data.

You can also access the influx backend via https://telemetry.b4mad.racing/ 
ping me on discord https://discord.com/invite/MaUQuSGSbJ for access credentials

**Comment by adenoz** [comment]
Hey thanks. I'll take a look. Can't promise when that'll be as I have a bunch on for at least the next few weeks.

**Comment by durandom** [comment]
we have an initial implemantion at https://github.com/b4mad/racing/blob/main/notebooks/fast_lap_analysis-v2.ipynb
