### ISSUE TITLE
aicoe-ci overlay build fails

### ISSUE THREAD

**Issue by goern** [b4mad/racing#95]
for tag v0.1.1. the build failed, see https://tekton.operate-first.cloud/#/namespaces/opf-ci-pipelines/pipelineruns/racing-paddock-65a091?pipelineTask=overlay-release-run&step=generate

```
+ '[' Containerfile == Dockerfile ']'
+ '[' -z '' ']'
+ /usr/local/bin/s2i build . --env IMAGE_NAME=quay.io/b4mad/paddock --env IMAGE_TAG=v0.1.1 --env THAMOS_RUNTIME_ENVIRONMENT=paddock --env THOTH_ADVISE=0 --env THOTH_ERROR_FALLBACK=1 --env THOTH_DRY_RUN=1 --env THAMOS_DEBUG=0 --env THAMOS_VERBOSE=1 --env THOTH_PROVENANCE_CHECK=0 --env GIT_REPO_NAME=racing --loglevel=0 --as-dockerfile /gen-source/Containerfile
ERROR: Required value not specified for "builderImage"
```

/kind bug
/priority important-soon

@harshad16 if you got some 15min to share, I would be happy if you can take a look at

**Comment by harshad16** [comment]
@goern  There are couple of things:

1. In overlays build Containerfile support was not there. 
 - It is fixed now, i have included it.
 
 2. For deploy https://github.com/b4mad/racing/blob/3758c3c8f46e37d0b596cbe1c5edf5cbdc0cca49/.aicoe-ci.yaml#L13
 part to work, `sesheta` should have write privileges on the repo. 
 
The build is fixed and image is pushed. 
https://quay.io/repository/b4mad/paddock?tab=tags

**Comment by goern** [comment]
@harshad16 if you need more fun projects for the weekend: https://discord.gg/tTe9y3Xq
your work is always appreciated!!
