### ISSUE TITLE
Deliver Container Image

### ISSUE THREAD

**Issue by goern** [b4mad/racing#98]
Hey, AICoE-CI!

Please build and deliver the following git tag:

Tag: 0.1.1

**Comment by goern** [comment]
@harshad16 should this have been closed with a comment that the pipelinerun failed? due to 'tag does not exist' ?

**Comment by harshad16** [comment]
We don't have the feature for commenting in case of error.
It would require some work.

**Comment by goern** [comment]
I see, thanks!

/close
